config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  ## PUBLIC PAGES
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/support', to: 'static_pages#support', via: 'get'
  match '/email_validate', to: 'email_validation#validation', via: 'post'

  ## PRIVATE PAGES

  # onboarding
  match '/mass_create', to: 'businesses#mass_create', via: :post, as: 'mass_create'

  # app

  match '/customer_feedbacks/new', to: 'customer_feedbacks#new', via: 'get', as: 'new_customer_feedback'

  match 'features/get_sub_features', to: 'features#get_sub_features', via: 'post'

  match '/discussions', to: 'discussions#index', via: 'get', as: 'discussions'
  match '/discussions/new', to: 'discussions#new', via: 'get', as: 'new_discussion'
  match '/discussions/load_more', to: 'discussions#load_more', via: 'get', as: 'more_discussions'
  match '/discussions/:id', to: 'discussions#show', via: 'get', as: 'discussion'

  match '/notes', to: 'notes#index', via: 'get', as: 'notes'
  match '/notes/new', to: 'notes#new', via: 'get', as: 'new_note'
  match '/notes/:id', to: 'notes#show', via: 'get', as: 'note'
  match '/notes/:id/edit', to: 'notes#edit', via: 'get', as: 'edit_note'

  match '/to-do-lists/new', to: 'user_tasks#new', via: 'get', as: 'new_to_do_list'
  match '/to-do-lists', to: 'user_tasks#index', via: 'get', as: 'to_do_lists'
  match '/to-do-lists/archived', to: 'user_tasks#index', via: 'get', as: 'archived_to_do_lists'
  match '/sub_tasks/clear_today', to: 'sub_tasks#clear_today', via: 'post', as: 'clear_todays_tasks'
  match '/to-do-lists/:id', to: 'user_tasks#show', via: 'get', as: 'to_do_list'
  match '/sub_tasks/(:scope)/(:id)', to: 'sub_tasks#index', via: :get, as: 'sub_tasks'


  match '/sub-features/:id/feedbacks', to: 'components#feedbacks', via: :get, as: 'component_feedbacks'

  match '/customer-insights/:id', to: 'customer_feedbacks#show', via: 'get', as: 'customer_insight'
  match '/customer_feedbacks/remove_references/:id', to: 'customer_feedbacks#remove_references', via: 'get', as: 'remove_references'
  match '/customer_feedbacks/revoke_decision/:id', to: 'customer_feedbacks#revoke_decision', via: 'get', as: 'revoke_decision'
  match '/customer_feedbacks/(:scope)/(:tool)', to: 'customer_feedbacks#index', via: 'get', as: 'customer_feedbacks'

  match '/to-dos/:id', to: 'sub_tasks#show', via: :get, as: 'to_do'
  match '/milestones/:id', to: 'main_activities#show', via: :get, as: 'milestone'
  match '/cores/:id', to: 'comp_advantages#show', via: :get, as: 'core'
  match '/business-models/:id', to: 'pricing_models#show', via: :get, as: 'business_model'
  match '/pricing-plans/:id', to: 'pricing_plans#show', via: :get, as: 'pricing_plan'


  match '/onboarding', to: 'dynamic_pages#onboarding', via: 'get', as: 'onboarding'
  match '/app/(:view)', to: 'tool_pages#app', via: 'get', as: 'app'
  match '/make', to: 'dynamic_pages#make', via: 'get', as: 'make'
  match '/settings', to: 'dynamic_pages#settings', via: 'get', as: 'settings'
  match '/home', to: 'dynamic_pages#home', via: 'get', as: 'home'
  match '/toolkit', to: 'dynamic_pages#toolkit', via: 'get', as: 'toolkit'
  match '/strategy-toolkit', to: 'dynamic_pages#strategy_toolkit', via: 'get', as: 'strategy_toolkit'
  match '/milestones', to: 'dynamic_pages#milestones', via: 'get', as: 'milestones'
  match '/team', to: 'dynamic_pages#team', via: 'get', as: 'team'
  match '/customer-insights', to: 'dynamic_pages#customer_insights', via: 'get', as: 'customer_insights'

  match '/chat', to: 'dynamic_pages#chat', via: 'get', as: 'chat'
  match '/products', to: 'dynamic_pages#products', via: 'get', as: 'products_dashboard'
  match '/markets', to: 'dynamic_pages#markets', via: 'get', as: 'markets'
  match '/welcome', to: 'dynamic_pages#welcome', via: 'get', as: 'welcome'
  match '/four-pillars', to: 'dynamic_pages#four_pillars', via: 'get', as: 'four_pillars'
  match '/top-pitfalls', to: 'dynamic_pages#top_pitfalls', via: 'get', as: 'top_pitfalls'


  # ADMIN
  match '/returning_users', to: 'static_pages#returning_users', via: 'get', as: 'returning_users'


  # SCRIPTS
  match '/invite_cofounders', to: 'memberships#invite_cofounders', via: 'get', as: 'invite_cofounders'
  match '/products/update_stage', to: 'products#update_stage', via: 'put', as: 'update_stage'

  match '/refresh_activity_feed', to: 'dynamic_pages#refresh_activity_feed', via: 'get', as: 'refresh_activity_feed'

  match 'delete_business/:id', to: 'businesses#delete_business', via: 'get', as: :delete_business


  ## switch beachhead and products

  match '/update_beachhead', to: 'beachheads#update', via: 'put', as: 'update_beachhead'
  match '/switch_product', to: 'active_products#update', via: 'put', as: 'switch_product'

  ## rank persona details
  match '/persona_details/:id/rank', to: 'persona_details#rank', via: 'put', as: 'persona_details_rank'


  ## STRIPE PAYMENT GATEWAY
  match '/my_account', to: 'subscriptions#my_account', via: 'get', as: 'account'
  match '/new_subscription', to: 'subscriptions#create', via: 'post', as: 'new_subscription'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  match '/cancel_subscription', to: 'subscriptions#cancel', via: [:get, :post]
  match '/unsubscribe', to: 'subscriptions#unsubscribe', via: 'get', as: 'unsubscribe'
  mount StripeEvent::Engine, at: '/webhooks'

  ## EMAIL RECIEVING

  # match '/email_processor', to: 'emails#create', via: :post

  match '/email_processor', to: 'griddler/emails#create', via: :post


  ## DEVISE ROUTES

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    match '/sign_up', to: 'users/registrations#new', via: 'get', as: 'sign_up'
    match '/sign_in', to: 'users/sessions#new', via: 'get', as: 'sign_in'
    match '/sign_out', to: 'users/sessions#destroy', via: 'get'
    match '/delete_account', to: 'users/registrations#delete_account', via: 'post', as: 'delete_account'
    match '/forgot_password', to: 'users/passwords#new', via: 'get', as: 'forgot_password'
    match '/users_time_zone', to: 'users/registrations#users_time_zone', via: 'post'
    match '/update_missing_data', to: 'users/registrations#update_missing_data', via: 'post'
  end


  ## SIDEKIQ WEB INTERFACE

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get '.well-known/acme-challenge/AmyfUECPpG2ZdFsbTiXkAw4GSfVWPtKFM9IqYLCYKsA', to: 'static_pages#lets_encrypt'

  ## RESOURCES

  # CREATE ONLY

  resources :usage_durations, :opinions, only: [:create]

  # CREATE, UPDATE, DESTROY, INDEX

  resources :products

  # CREATE, UPDATE, DESTROY

  resources :businesses, :business_parameters, :endusers, :personas, :persona_details, :benefits,
            :value_metrics, :next_customers, :pricing_models, :sales_strategies, :comp_advantages,
            :comp_positions, :procurement_steps, :pitches, :relationship_steps, :cx_steps,
            :feedbacks, :key_activities, :features, :main_activities, :improvements,
            :innovations, :attractions, :pricing_plans, :iterations, :strategy_gaps, :user_priorities,
            :plan_defects, :sub_tasks, :experiments, :memberships, :messages, :customers, :issues,
            :components, :customer_feedbacks, :sub_components, :checklist_items, :dashboards, only: [:create, :update, :destroy]

  resources(:discussions, :notes, :customer_feedbacks, :user_tasks, :sub_tasks,
            :main_activities, :comp_advantages, :pricing_models, :pricing_plans,
            only: [:create, :update, :destroy]) do

    resources :comments, only: [:create, :update, :destroy]

  end


  # CREATE, UPDATE, DESTROY, AND EDIT

  resources :user_parameters, only: [:create, :update, :destroy, :edit]

  # ONLY UPDATE

  resources :touchpoints, :financials, :customer_decision_making_units, only: [:update]

  # ONLY SHOW

  resources :referrals, only: [:show]


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  include ApplicationHelper

  include AnalyticsHelper

  before_action :validate_user, only: [:account, :elevator_pitch, :faqs]

  before_action :validate_admin, only: [:returning_users]

  layout 'home', only: [:home, :about, :pricing, :privacy, :terms, :support]

  def lets_encrypt
    render text: 'AmyfUECPpG2ZdFsbTiXkAw4GSfVWPtKFM9IqYLCYKsA.eg0xjB5WWIQ3CyaXJ5u9i6yPcdcKYP8yYFUMhuIKz-k'
  end

  def home

  end

  def pricing

  end

  def support

  end


  def about

  end

  def privacy

  end

  def terms

  end

  def admin_stats

  end

  def returning_users

    permitted_scopes = ['all', 'recently_active']

    if permitted_scopes.include? params[:filter]
      @users = User.includes(:user_parameter).send(params[:filter])
      send_data generate_csv(@users)
    end

  end


  private


  def validate_admin
    unless current_user.admin?
      redirect_to app_path
    end
  end

  def validate_user
    if user_signed_in?

      # when re enabled check whether a momentary error is shown on sign up because
      # the trial expiry is set by the background process

      if current_user.trial_expiry_date && current_user.expired_trial_user? && !current_user.active_subscriber?
        flash[:notice] = "Your trial expired on #{ldt(current_user.trial_expiry_date)}. Please subscribe to continue."
        # redirect_to account_path
      elsif current_user.former_subscriber?
        flash[:notice] = "Your need to subscribe in order to access EdisonPlan."
        # redirect_to account_path
      end

    else
      redirect_to sign_in_path
      flash[:notice] = "Please sign in to access the app"
    end

  end

end

app/views/static_pages/shared/_alt_header.html.erb
<header class="app-header <%= 'no-product' unless active_product %>" style="">
  <% if active_product %>
      <div class="header-top">

        <ul class="tab-list">

          <li id="home_tab" data-behaviour="open_in_new_tab" data-href="<%= home_path %>" data-tab-href="<%= home_path %>" class="row <%= 'active' if @view == 'home' %>" style="line-height: 30px;">
            <%= fa_icon 'home' %>
            <span class="inner" style="display: none;">Home</span>
          </li>

          <% if @view && @view != 'home' %>
              <%= header_tab_item @view.humanize.titleize, active: true %>
          <% elsif @sub_tool_title || @new_sub_tool_title %>
              <%= header_tab_item @sub_tool_title || @new_sub_tool_title, active: true %>
          <% end %>

          <li class="new-task-header-btn">
            <div class="dropdown">
              <div id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                +
                <span class="caret"></span>
              </div>
              <ul class="dropdown-menu" aria-labelledby="dLabel">
                <li data-behaviour="clone_target_in_new_tab" data-tool-type="discussion">New Discussion</li>
                <li data-behaviour="clone_target_in_new_tab" data-tool-type="to-do-list">New To do List</li>
                <li data-behaviour="clone_target_in_new_tab" data-tool-type="note">New Note</li>
              </ul>
            </div>

          </li>

        </ul>

        <ul class="list-inline options-list">
          <li>
            <span class='support-link' data-behaviour='new_feedback'>Support</span>
          </li>
          <!--<li>-->
          <!--<%#= render 'messages/header_messages' if active_product %>-->
          <!--</li>-->
        </ul>

      </div>
      <div class="header-bottom">
        <div class="row sub-tools">


          <div class="beachhead-indicator">

          </div>

          <div class="quick-find-enc">

            <input class="form-control" id="quick_find" data-behaviour="show_resource_list" value="" placeholder="Quick find"/>

            <div style="display: none;" class="resource-items-container">
              <ul>
                <li class="resource-section"><strong>to do lists</strong></li>
                <% active_product.user_tasks.pending.each do |task| %>
                    <li data-behaviour="open_in_new_tab" data-href="<%= task.friendly_link %>" class="resource-item"><%= ae_live_field task, :task_name %></li>
                <% end %>
                <li class="resource-section"><strong>notes</strong></li>
                <% active_product.notes.each do |note| %>
                    <li data-behaviour="open_in_new_tab" data-href="<%= note.friendly_link %>" class="resource-item"><%= ae_live_field note, :title %></li>
                <% end %>
                <li class="resource-section"><strong>discussions</strong></li>
                <% active_product.discussions.each do |discussion| %>
                    <li data-behaviour="open_in_new_tab" data-href="<%= discussion.friendly_link %>" class="resource-item"><%= ae_live_field discussion, :title %></li>
                <% end %>
              </ul>
            </div>
          </div>

          <div class="col-xs-12 tool-btn-group">

            <div class="sub-tool-btns">
              <div class="btn-group">
                <div data-behaviour="open_in_new_tab" data-href="<%= customer_insights_path %>" class="tool-card">insights</div>
                <div class="tool-card-add" data-behaviour="clone_target_in_new_tab" data-tool-type="insight">+</div>
              </div>
              <div class="btn-group">
                <div data-behaviour="open_in_new_tab" data-href="<%= discussions_path %>" class="tool-card">discussions</div>
                <div class="tool-card-add" data-behaviour="clone_target_in_new_tab" data-tool-type="discussion">+</div>
              </div>
              <div class="btn-group">
                <div data-behaviour="open_in_new_tab" data-href="<%= to_do_lists_path %>" class="tool-card">to-dos</div>
                <div class="tool-card-add" data-behaviour="clone_target_in_new_tab" data-tool-type="to-do-list">+</div>
              </div>
              <div class="btn-group">
                <div data-behaviour="open_in_new_tab" data-href="<%= notes_path %>" class="tool-card">notes</div>
                <div class="tool-card-add" data-behaviour="clone_target_in_new_tab" data-tool-type="note">+</div>
              </div>

              <div class="btn-group" style="position: absolute;right: 90px;">
                <div data-behaviour="open_in_new_tab" data-href="<%= strategy_toolkit_path %>" class="tool-card" style="border-radius: 5px">Strategy Toolkit</div>
              </div>

            </div>



          </div>




        </div>
      </div>
  <% else %>


      <div id="edison-logo">
        <%= image_tag 'oneLogo.jpg' %>
      </div>

      <div>
        <%= button_to sign_out_path, method: :get, form_class: 'header-sign-out-form' do %>
            Sign Out
        <% end %>
      </div>

  <% end %>
</header>

app/views/static_pages/shared/_bip_view_modal_skeleton.html.erb
<div class="modal fade bip-view full-page" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog center-modal-dialog modal-md">
    <div class="modal-content clearfix">
      <div class="modal-header">
        <div class="modal-title"></div>
      </div>
      <div class="modal-body">
        <div class="modal-text"></div>
        <div class="modal-edit-enc"></div>
      </div>

      <div class="modal-footer">
        <button class="modal-got-it">Got it!</button>
        <button class="modal-close" data-dismiss="modal">Done</button>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/shared/_canvas_item.html.erb
<div class="canvas-component" data-behaviour="open_in_new_tab" data-href="<%= app_path(view: STEP[step][:name].parameterize) %>">


  <div class="icon">
    <div class="canvas-icon <%= "_#{icon}" %>"></div>
  </div>


  <div class="title">
    <%= title %>
  </div>
  <hr class="mini-break">

  <div class="result">
    <%= StaticPagesHelper::QUESTION_FIELDS[step][:question] %>
  </div>

  <div class="canvas-card-checklist">
    <div class="checklist-progress-bar" data-toggle="tooltip" title="<%= checklist_score step %> out of 7 items from the checklist is complete">
      <div class="inner" style="width: <%= prog =  (checklist_score(step)/7.0*100).round  %>%">
      </div>
    </div>
    <div style="margin-top: 5px;"><%= prog %> % complete</div>
  </div>


</div>

app/views/static_pages/shared/_delete_user_confirmation.html.erb
<% if current_user.active_subscriber? || current_user.unpaid_subscriber? %>
    <div class="modal-header">
      <div class="modal-title">Delete Account</div>
    </div>
    <div class="modal-body business-delete-bg">
      <h4 class="confirm-title">You are a paid subscriber. You need to cancel your subscription before you delete your account.</h4>
      <div style="margin-top:30px;"><%= link_to 'Go to My Account', account_path %></div>
    </div>
    <div class="modal-footer">
      <div class="btn-container">
        <button type="button" class="choice-btn" data-dismiss="modal" aria-label="Close">Close</button>
      </div>
    </div>
<% else %>
    <div class="modal-header">
      <div class="modal-title">Delete Account</div>
    </div>
    <p class="bg-danger"><strong>Important: </strong>Your account cannot be recovered if you delete it.</p>
    <div class="modal-body business-delete-bg">
      <div class="modal-title">Are you sure you want to delete your account?</div>
    </div>
    <div class="modal-footer">
      <div class="btn-container">
        <%= button_to "Delete...", registration_path(current_user), method: :delete, class: "no-btn" %>
        <div></div>
        <button type="button" class="btn btn-primary" data-dismiss="modal" aria-label="Close">Close</button>
      </div>
    </div>
<% end %>

app/views/static_pages/shared/_home_center_col.html.erb
<div class="home-center-column">

  <% if current_user.profile_missing? %>
      <%= render 'static_pages/shared/profile_missing' %>
  <% end %>

  <% discussions = active_product.discussions %>


  <div class="front-page-discussions-list-enc">

    <% if discussions.count == 0 %>

        <div class="first-time-note blue-note">
          <h4>How to implement the four startup best practices?
          </h4>
          <hr>
          <ol>
            <li><strong>Strategy</strong>: Build a customer responsive business
              <span class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= strategy_toolkit_path %>">strategy</span>.
            </li>
            <li><strong>Insights</strong>: Get outdoors to meet customers often and gather
              <span class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= customer_insights_path %>">insights</span>.
            </li>
            <li><strong>Product</strong>: Solve customers’ unmet needs and grow the
              <span class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= make_path %>">product</span>.
            </li>
            <li><strong>Customers</strong>: Commit to early and continuous
              <span class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= step_href_path 15 %>">customer</span>
              recruitment.
            </li>
          </ol>
        </div>

        <div style="padding: 10px;text-align: center;">
          <div data-behaviour="clone_target_in_new_tab" data-tool-type="discussion" class="hyperlink">
            I want to start a discussion about this with my team
          </div>
        </div>


    <% else %>
        <div class="front-page-discussions-list">
          <% discussions.includes(:user).limit(15).each do |discussion| %>
              <%= render 'discussions/new_fp_discussion', discussion: discussion %>
          <% end %>
        </div>
    <% end %>

    <% if discussions.count > 20 %>
        <div style="margin-top: 10px; text-align: center;" class="fp-discussion-load-more">
          <div class="hyperlink" data-behaviour="load_more" data-target="[data-fp-discussion-id]">load more</div>
        </div>
    <% end %>

  </div>

  <% unless active_product.welcome_msg_read %>

      <script>
        $(function () {
          $('.welcome-modal').modal('show')
        });
      </script>

      <div class="modal welcome-modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Welcome to EdisonPlan</h4>
            </div>
            <div class="modal-body">
              <p>Hey! These four best practices helps in building a customer-driven startup.</p>

              <ol>
                <li>A customer responsive business strategy</li>
                <li>Get outdoors to meet customers often</li>
                <li>Grow the product with customers’ unmet needs</li>
                <li>Early and continuous customer recruitment</li>
              </ol>

              <p style="margin-top: 30px">EdisonPlan provides four tools to implement these best practices,
                everyday.</p>

              <div data-dismiss="modal" style="margin-top: 10px" class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= strategy_toolkit_path %>">Strategy</div>
              <div data-dismiss="modal" style="margin-top: 10px" class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= customer_insights_path %>">Feedback</div>
              <div data-dismiss="modal" style="margin-top: 10px" class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= make_path %>">Product</div>
              <div data-dismiss="modal" style="margin-top: 10px" class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= step_href_path(15) %>">Customers</div>


              <p style="margin-top: 30px">Explore them and win fast with the All New EdisonPlan</p>

              <p class="hyperlink" data-target=".complete_modal" data-behaviour="mirror_click" data-href="<%= home_path %>" style="margin-top: 30px">Go
                to the dashboard</p>

            </div>
            <div class="modal-footer">
              <%= button_to 'Dismiss', product_path(active_product.id, product: {welcome_msg_read: true}), remote: true, class: ' btn btn-default complete_modal', method: :put %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

  <% end %>


</div>

app/views/static_pages/shared/_new_resource_form.html.erb
<% if has_valid_access? %>
    <%= form_for parent.send(resources).build, remote: true, html: {class: 'resource-form'} do |f| %>
        <div id="form-error-container"></div>
        <%= f.text_field field.to_sym, placeholder: "#{placeholder}", class: "normal-input" %>
        <%= f.submit "+", class: "add-submit", disabled: 'disabled' %>
    <% end %>
<% end %>

app/views/static_pages/shared/_new_resource_form2.html.erb
<div class="form-container">

  <div class="btn btn-link btn-xs" data-behaviour="show_form">+ Include a <%= options[:generic_item_name] || 'row' %></div>

  <% if has_valid_access? %>
      <%= form_for parent.send(resources.to_s.pluralize).build, remote: true, html: {class: 'resource-form'} do |f| %>
          <%= f.text_field field, placeholder: "#{options[:placeholder]}", class: "normal-input", autocomplete: "off" %>
          <% if options[:hidden_field].present? %>
              <%= f.hidden_field options[:hidden_field], value: options[:hf_value] %>
          <% end %>
          <% if options[:hidden_field2].present? %>
              <%= f.hidden_field options[:hidden_field2], value: options[:hf_value2] %>
          <% end %>
          <% if options[:hidden_field3].present? %>
              <%= f.hidden_field options[:hidden_field3], value: options[:hf_value3] %>
          <% end %>
          <%= button_tag "+", class: "add-submit", 'data-disable-with' => disabled_spinner %>
          <div class="btn btn-link " data-behaviour="hide_form">I'm done adding rows</div>
      <% end %>
  <% end %>
</div>

app/views/static_pages/shared/_new_resource_form_modern.html.erb
<div class="new-resource-form-modern">
  <span data-behaviour='show_new_resource_form'><%= button_name %></span>
  <div class="form-enc">
    <% if has_valid_access? %>
        <%= form_for parent.send(resources.to_s.pluralize).build, remote: true, html: {class: 'resource-form'} do |f| %>
            <%= f.text_field field, placeholder: "#{options[:placeholder]}", class: "normal-input", autocomplete: "off" %>
            <% if options[:hidden_field].present? %>
                <%= f.hidden_field options[:hidden_field], value: options[:hf_value] %>
            <% end %>
            <% if options[:hidden_field2].present? %>
                <%= f.hidden_field options[:hidden_field2], value: options[:hf_value2] %>
            <% end %>
            <% if options[:hidden_field3].present? %>
                <%= f.hidden_field options[:hidden_field3], value: options[:hf_value3] %>
            <% end %>
            <%= button_tag "+", class: "add-submit" %>
  <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/shared/_sheet_item.html.erb
<div class="canvas-sheet-item">

  <div class="title heading">
    <%= StaticPagesHelper::QUESTION_FIELDS[step][:question] %>
  </div>

  <div class="result">
    <%= active_edit_if has_valid_access?, beachhead, StaticPagesHelper::QUESTION_FIELDS[step][:field], placeholder: StaticPagesHelper::QUESTION_FIELDS[step][:placeholder] %>
  </div>

  <div style="margin-top: 20px;text-align: right;">
    <div class="btn btn-xs btn-link" data-behaviour="open_in_new_tab" data-href="<%= app_path(view: STEP[step][:name].parameterize) %>">
      Go to the <%= STEP[step][:name]  %> tool &rarr;
    </div>
  </div>


  <hr class="mini-break">
</div>

app/views/static_pages/shared/_step_footer.html.erb
<div class="step-footer">

  <ul class="footer-list">
    <li class="hyperlink" data-behaviour="clone_target_in_new_tab" data-tool-type="discussion">I want to discuss this
      tool with my team
    </li>
    <li class="hyperlink" data-behaviour="clone_target_in_new_tab" data-tool-type="to-do-list">I want to make a to-do
      list for stuff that needs to be done
    </li>
    <li class="hyperlink" data-behaviour="clone_target_in_new_tab" data-tool-type="note">I want to write down a thought
      about this tool
    </li>
    <li class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= strategy_toolkit_path %>">Back to the canvas
    </li>
  </ul>

</div>

app/views/static_pages/shared/_toolgroup_product_iteration_body.html.erb
<div style=" margin: 20px 0;"  class="dashed-box">
  <% rp = beachhead.release_progress %>

  <div style="font-size: 1rem;margin-bottom: 10px;">Product Build Status</div>


  <div class="prog-bar-container">
    <div class="edison-progress-bar">
      <div class="prog-bar-inner" style="width: <%= [rp[2], 1].max %>%;"></div>
      <div class="prog-bar-inner ongoing" style="width: <%= rp[1] %>%;"></div>
    </div>
  </div>
  <div class="progress-words" style="margin-top: 5px;font-size: .8rem;">
    <%= rp[2] %>% complete | <%= rp[1] %>% ongoing | <%= 100 - ( rp[1] + rp[2] ) %>% pending
  </div>

  <% if beachhead.projected_date %>
      <div class="projected-completion-date" style="margin-top: 20px;">
        <div>Estimated Completion Date</div>
        <span style="font-size: 1rem;"><%= ldt(beachhead.projected_date) %></span>
      </div>
  <% end %>

  <div style="margin-top: 10px;" class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= make_path %>">Go to Product Roadmap</div>

</div>