config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  ## PUBLIC PAGES
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/support', to: 'static_pages#support', via: 'get'
  match '/email_validate', to: 'email_validation#validation', via: 'post'

  ## PRIVATE PAGES

  # onboarding
  match '/mass_create', to: 'businesses#mass_create', via: :post, as: 'mass_create'

  # app

  match '/customer_feedbacks/new', to: 'customer_feedbacks#new', via: 'get', as: 'new_customer_feedback'

  match 'features/get_sub_features', to: 'features#get_sub_features', via: 'post'

  match '/discussions', to: 'discussions#index', via: 'get', as: 'discussions'
  match '/discussions/new', to: 'discussions#new', via: 'get', as: 'new_discussion'
  match '/discussions/load_more', to: 'discussions#load_more', via: 'get', as: 'more_discussions'
  match '/discussions/:id', to: 'discussions#show', via: 'get', as: 'discussion'

  match '/notes', to: 'notes#index', via: 'get', as: 'notes'
  match '/notes/new', to: 'notes#new', via: 'get', as: 'new_note'
  match '/notes/:id', to: 'notes#show', via: 'get', as: 'note'
  match '/notes/:id/edit', to: 'notes#edit', via: 'get', as: 'edit_note'

  match '/to-do-lists/new', to: 'user_tasks#new', via: 'get', as: 'new_to_do_list'
  match '/to-do-lists', to: 'user_tasks#index', via: 'get', as: 'to_do_lists'
  match '/to-do-lists/archived', to: 'user_tasks#index', via: 'get', as: 'archived_to_do_lists'
  match '/sub_tasks/clear_today', to: 'sub_tasks#clear_today', via: 'post', as: 'clear_todays_tasks'
  match '/to-do-lists/:id', to: 'user_tasks#show', via: 'get', as: 'to_do_list'
  match '/sub_tasks/(:scope)/(:id)', to: 'sub_tasks#index', via: :get, as: 'sub_tasks'


  match '/sub-features/:id/feedbacks', to: 'components#feedbacks', via: :get, as: 'component_feedbacks'

  match '/customer-insights/:id', to: 'customer_feedbacks#show', via: 'get', as: 'customer_insight'
  match '/customer_feedbacks/remove_references/:id', to: 'customer_feedbacks#remove_references', via: 'get', as: 'remove_references'
  match '/customer_feedbacks/revoke_decision/:id', to: 'customer_feedbacks#revoke_decision', via: 'get', as: 'revoke_decision'
  match '/customer_feedbacks/(:scope)/(:tool)', to: 'customer_feedbacks#index', via: 'get', as: 'customer_feedbacks'

  match '/to-dos/:id', to: 'sub_tasks#show', via: :get, as: 'to_do'
  match '/milestones/:id', to: 'main_activities#show', via: :get, as: 'milestone'
  match '/cores/:id', to: 'comp_advantages#show', via: :get, as: 'core'
  match '/business-models/:id', to: 'pricing_models#show', via: :get, as: 'business_model'
  match '/pricing-plans/:id', to: 'pricing_plans#show', via: :get, as: 'pricing_plan'


  match '/onboarding', to: 'dynamic_pages#onboarding', via: 'get', as: 'onboarding'
  match '/app/(:view)', to: 'tool_pages#app', via: 'get', as: 'app'
  match '/make', to: 'dynamic_pages#make', via: 'get', as: 'make'
  match '/settings', to: 'dynamic_pages#settings', via: 'get', as: 'settings'
  match '/home', to: 'dynamic_pages#home', via: 'get', as: 'home'
  match '/toolkit', to: 'dynamic_pages#toolkit', via: 'get', as: 'toolkit'
  match '/strategy-toolkit', to: 'dynamic_pages#strategy_toolkit', via: 'get', as: 'strategy_toolkit'
  match '/milestones', to: 'dynamic_pages#milestones', via: 'get', as: 'milestones'
  match '/team', to: 'dynamic_pages#team', via: 'get', as: 'team'
  match '/customer-insights', to: 'dynamic_pages#customer_insights', via: 'get', as: 'customer_insights'

  match '/chat', to: 'dynamic_pages#chat', via: 'get', as: 'chat'
  match '/products', to: 'dynamic_pages#products', via: 'get', as: 'products_dashboard'
  match '/markets', to: 'dynamic_pages#markets', via: 'get', as: 'markets'
  match '/welcome', to: 'dynamic_pages#welcome', via: 'get', as: 'welcome'
  match '/four-pillars', to: 'dynamic_pages#four_pillars', via: 'get', as: 'four_pillars'
  match '/top-pitfalls', to: 'dynamic_pages#top_pitfalls', via: 'get', as: 'top_pitfalls'


  # ADMIN
  match '/returning_users', to: 'static_pages#returning_users', via: 'get', as: 'returning_users'


  # SCRIPTS
  match '/invite_cofounders', to: 'memberships#invite_cofounders', via: 'get', as: 'invite_cofounders'
  match '/products/update_stage', to: 'products#update_stage', via: 'put', as: 'update_stage'

  match '/refresh_activity_feed', to: 'dynamic_pages#refresh_activity_feed', via: 'get', as: 'refresh_activity_feed'

  match 'delete_business/:id', to: 'businesses#delete_business', via: 'get', as: :delete_business


  ## switch beachhead and products

  match '/update_beachhead', to: 'beachheads#update', via: 'put', as: 'update_beachhead'
  match '/switch_product', to: 'active_products#update', via: 'put', as: 'switch_product'

  ## rank persona details
  match '/persona_details/:id/rank', to: 'persona_details#rank', via: 'put', as: 'persona_details_rank'


  ## STRIPE PAYMENT GATEWAY
  match '/my_account', to: 'subscriptions#my_account', via: 'get', as: 'account'
  match '/new_subscription', to: 'subscriptions#create', via: 'post', as: 'new_subscription'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  match '/cancel_subscription', to: 'subscriptions#cancel', via: [:get, :post]
  match '/unsubscribe', to: 'subscriptions#unsubscribe', via: 'get', as: 'unsubscribe'
  mount StripeEvent::Engine, at: '/webhooks'

  ## EMAIL RECIEVING

  # match '/email_processor', to: 'emails#create', via: :post

  match '/email_processor', to: 'griddler/emails#create', via: :post


  ## DEVISE ROUTES

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    match '/sign_up', to: 'users/registrations#new', via: 'get', as: 'sign_up'
    match '/sign_in', to: 'users/sessions#new', via: 'get', as: 'sign_in'
    match '/sign_out', to: 'users/sessions#destroy', via: 'get'
    match '/delete_account', to: 'users/registrations#delete_account', via: 'post', as: 'delete_account'
    match '/forgot_password', to: 'users/passwords#new', via: 'get', as: 'forgot_password'
    match '/users_time_zone', to: 'users/registrations#users_time_zone', via: 'post'
    match '/update_missing_data', to: 'users/registrations#update_missing_data', via: 'post'
  end


  ## SIDEKIQ WEB INTERFACE

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get '.well-known/acme-challenge/AmyfUECPpG2ZdFsbTiXkAw4GSfVWPtKFM9IqYLCYKsA', to: 'static_pages#lets_encrypt'

  ## RESOURCES

  # CREATE ONLY

  resources :usage_durations, :opinions, only: [:create]

  # CREATE, UPDATE, DESTROY, INDEX

  resources :products

  # CREATE, UPDATE, DESTROY

  resources :businesses, :business_parameters, :endusers, :personas, :persona_details, :benefits,
            :value_metrics, :next_customers, :pricing_models, :sales_strategies, :comp_advantages,
            :comp_positions, :procurement_steps, :pitches, :relationship_steps, :cx_steps,
            :feedbacks, :key_activities, :features, :main_activities, :improvements,
            :innovations, :attractions, :pricing_plans, :iterations, :strategy_gaps, :user_priorities,
            :plan_defects, :sub_tasks, :experiments, :memberships, :messages, :customers, :issues,
            :components, :customer_feedbacks, :sub_components, :checklist_items, :dashboards, only: [:create, :update, :destroy]

  resources(:discussions, :notes, :customer_feedbacks, :user_tasks, :sub_tasks,
            :main_activities, :comp_advantages, :pricing_models, :pricing_plans,
            only: [:create, :update, :destroy]) do

    resources :comments, only: [:create, :update, :destroy]

  end


  # CREATE, UPDATE, DESTROY, AND EDIT

  resources :user_parameters, only: [:create, :update, :destroy, :edit]

  # ONLY UPDATE

  resources :touchpoints, :financials, :customer_decision_making_units, only: [:update]

  # ONLY SHOW

  resources :referrals, only: [:show]


end

app/models/pricing_plan.rb
class PricingPlan < ActiveRecord::Base

  belongs_to :business

  has_many :attractions, dependent: :destroy
  has_many :plan_defects, dependent: :destroy
  has_many :comments, dependent: :destroy

  default_scope { order('pricing_plans.created_at ASC') }

  validates :plan_name, length: {:maximum => 150}
  scope :for_stage, -> stage_no { where(stage: stage_no) }

  delegate :product, to: :business


  validates :product_price, numericality: {allow_blank: true, less_than_or_equal_to: 100_000_000}
  validates :ltv, numericality: {allow_blank: true, less_than_or_equal_to: 1_000_000_000}
  validates :competitor_price_lb, numericality: {allow_blank: true, less_than_or_equal_to: 100_000_000}
  validates :competitor_price_ub, numericality: {allow_blank: true, less_than_or_equal_to: 100_000_000}


  include CommentsHelper::InstanceMethods

  after_create :generate_secret_token


  def friendly_link
    "/pricing-plans/#{id}"
  end

  def title_for_email
    plan_name
  end


end

app/controllers/pricing_plans_controller.rb
class PricingPlansController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_business, only: [:destroy, :update]


  def create
    @pricing_plan = beachhead.pricing_plans.build(pricing_plan_params)
    respond_to do |format|
      if @pricing_plan.save
        create_child_resources
        format.html { redirect_to :back }
        format.js
        record_event
      else
        format.html { redirect_to :back }
        format.js {}
      end
    end

  end

  def show
    item =  PricingPlan.where(id: params[:id]).first
    if item && current_user.has_access_to?(item)
      @sub_tool_resource = item
      @sub_tool_title = @sub_tool_resource.plan_name
      respond_to do |format|
        format.html
        format.js
      end
    else
      render status: 404
    end
  end

  def destroy

    respond_to do |format|
      @pricing_plan.destroy
      format.html { redirect_to :back }
      format.js
      record_event
    end

  end


  def update
    @params = params[:pricing_plan]
    respond_to do |format|
      if @pricing_plan.update_attributes(pricing_plan_params)
        format.json { respond_with_bip(@pricing_plan) }
        format.html { redirect_to :back }
        format.js { respond_with_active_edit @pricing_plan, @field }
        record_event
      else
        format.json { respond_with_bip(@pricing_plan) }
        format.html { redirect_to :back }
        format.js {}
      end
    end
  end

  private

  def create_child_resources
    3.times do |i|
      @pricing_plan.attractions.create(:attraction_name => "Attraction #{i+1}")
      @pricing_plan.plan_defects.create(:defect_name => "Defect #{i+1}")
    end
  end

  def pricing_plan_params
    params.require(:pricing_plan).permit(:plan_name,
                                         :preference,
                                         :model_adopted,
                                         :cust_group,
                                         :product_price,
                                         :invoice_timing,
                                         :billing_frequency,
                                         :competitor_price_lb,
                                         :competitor_price_ub,
                                         :price_proportion,
                                         :ltv, :stage)
  end


  def correct_business
    @pricing_plan = beachhead.pricing_plans.find_by(id: params[:id])
    if @pricing_plan.nil?
      redirect_to root_url
    else
      @obj = {id: @pricing_plan.id, obj_name: @pricing_plan.class.to_s.underscore}
    end
  end



  def record_event
    b = @pricing_plan.business
    EventRecorderWorker.perform_async(b.product_id, 1, current_user.id, 12, {business_id: b.id})
  end


end

app/views/pricing_plans/_new_pricing_plan_rec.html.erb
<div class="tool-section type-b" id="<%= object.row_selector(false) %>">
  <% step_name = object.underscored.to_sym %>
  <%= section_header index+1, object %>
  <div class="tool-child">
    <%= section_body object %>
    <%= section_break object.class.blueprint_for_section[:section_break_text] %>
    <% child_table = object.class.blueprint_for_section[:child_table] %>

    <% if child_table %>
        <% child_blueprint = child_table.to_s.camelize.constantize.blueprint_for_table %>
        <%= generate_table object, child_table, headers:child_blueprint[:headers] %>
        <%= render 'static_pages/shared/new_resource_form2', parent:object, resources: child_table, field: child_blueprint[:form_default_field], options: {placeholder:child_blueprint[:placeholder], hidden_field: instance_eval(':'+step_name.to_s+'_id'), hf_value: object.id} %>
    <% end %>

    <%= section_break object.class.blueprint_for_section[:section_break_text1] %>
    <% child_table2 = object.class.blueprint_for_section[:child_table1] %>
    <% if child_table2 %>
        <% child_blueprint = child_table2.to_s.camelize.constantize.blueprint_for_table %>
        <%= generate_table object, child_table2, headers:child_blueprint[:headers] %>
        <%= render 'static_pages/shared/new_resource_form2', parent:object, resources: child_table2, field: child_blueprint[:form_default_field], options: {placeholder:child_blueprint[:placeholder], hidden_field: instance_eval(':'+step_name.to_s+'_id'), hf_value: object.id} %>
    <% end %>
    <%= toolfooter %>
  </div>
</div>

app/views/pricing_plans/_pricing_plan_card.html.erb
<div class="card" data-object="pricing_plan" data-url="<%= pricing_plan_path pricing_plan.id %>" data-card-id="<%= r = rand_string %>">
  <div class="inner" data-toggle="modal" data-target=".board-modal._<%= r %>">

    <div class="card-title">
      <%= ae_live_field pricing_plan, :plan_name %>
      <%= delete_object pricing_plan %>
    </div>
    <hr class="mini-break">
    <div class="card-info-item">
      LTV: $<%= ae_live_field pricing_plan, :ltv, placeholder: '0' %>
    </div>
  </div>

  <div class="board-modal _<%= r %> modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">


        <%= render 'pricing_plans/pricing_plan_modal_content', pricing_plan: pricing_plan %>

      </div>
    </div>
  </div>

</div>

app/views/pricing_plans/_pricing_plan_modal_content.html.erb
<div class="card-modal-content-body">
  <div class="board-modal-title">
    <%= active_edit_if has_valid_access?, pricing_plan, :plan_name %>
  </div>
  <div class="board-modal-table">

    <div class="question-row">
      <div class="question-num"></div>
      <div class="table-header">Customer Group targeted by this Plan</div>
      <div class="white-text-snippet" style="padding: 4px 10px;display: inline-block;margin-top: 4px;"><%= active_edit_if has_valid_access?, pricing_plan, :cust_group, type: :select, choices: CUSTOMER_GROUPS %></div>
      <hr class="mini-break">
    </div>

    <div class="question-row">
      <div class="question-num"></div>
      <div class="table-header">Details of the pricing plan</div>
      <div class="" style="margin-top: 4px;">
        <div style="padding: 4px 10px;display: inline-block;" class="white-text-snippet"><%= active_edit_if has_valid_access?, pricing_plan, :product_price, {numeric: true, prefix: '$ ', placeholder: 'amount'} %></div>
        <div style="padding: 2px 10px;display: inline-block;" class="white-text-snippet"><%= active_edit_if has_valid_access?, pricing_plan, :billing_frequency, {type: :select, choices: {1 => 'per hour', 2 => 'per day', 3 => 'per week', 4 => 'per month', 5 => 'per annum'}, placeholder: 'frequency'} %></div>
        <div style="padding: 2px 10px;display: inline-block;" class="white-text-snippet"><%= active_edit_if has_valid_access?, pricing_plan, :invoice_timing, {type: :select, choices: {1 => 'before usage', 2 => 'after usage', 3 => 'during usage'}, placeholder: 'timing'} %></div>
      </div>
      <hr class="mini-break">
    </div>

    <div class="question-row">
      <div class="question-num"></div>
      <div class="table-header">Competitor price range</div>
      <div class="" style="margin-top: 4px;">
        <div style="display: inline-block;padding: 4px 10px; text-align: right;min-width: 100px;" class="white-text-snippet"><%= active_edit_if has_valid_access?, pricing_plan, :competitor_price_lb, {numeric: true, prefix: '$ ', placeholder: '$ 0'} %></div>
        -
        <div style="display: inline-block;padding: 4px 10px; text-align: right;min-width: 100px;" class="white-text-snippet"><%= active_edit_if has_valid_access?, pricing_plan, :competitor_price_ub, {numeric: true, prefix: '$ ', placeholder: '$ 0'} %></div>
      </div>
      <hr class="mini-break">
    </div>

    <div class="question-row">
      <div class="question-num"></div>
      <div class="table-header">Product's LTV under this plan</div>
      <div class="">
        <div style="display: inline-block;padding: 4px 10px; text-align: right;min-width: 100px;" class="white-text-snippet"><%= active_edit_if has_valid_access?, pricing_plan, :ltv, {numeric: true, prefix: '$ ', placeholder: '$ 0'} %></div>
      </div>
      <hr class="mini-break">
    </div>

    <div class="question-row">
      <div class="question-num"></div>
      <div class="table-header">Key Attractions of this plan</div>
      <div class="">
        <ul class="child-list" data-child="attraction" data-parent-id="pricing_plan_<%= pricing_plan.id %>">
          <% pricing_plan.attractions.each do |attraction| %>
              <li class=child-item><%= active_edit_if has_valid_access?, attraction, :attraction_name %></li>
          <% end %>
          <li><%= render 'static_pages/shared/new_resource_form2', parent: pricing_plan, resources: :attraction, field: :attraction_name, options: {placeholder: 'Include one more', hidden_field: :pricing_plan_id, hf_value: pricing_plan.id} %></li>
        </ul>
      </div>
      <hr class="mini-break">
    </div>

    <div class="question-row">
      <div class="question-num"></div>
      <div class="table-header">Key Defects in this plan</div>
      <div class="">
        <ul class="child-list" data-child="plan_defect" data-parent-id="pricing_plan_<%= pricing_plan.id %>">
          <% pricing_plan.plan_defects.each do |plan_defect| %>
              <li class="child-item"><%= active_edit_if has_valid_access?, plan_defect, :defect_name %></li>
          <% end %>
          <li><%= render 'static_pages/shared/new_resource_form2', parent: pricing_plan, resources: :plan_defect, field: :defect_name, options: {placeholder: 'Include one more', hidden_field: :pricing_plan_id, hf_value: pricing_plan.id} %></li>
        </ul>
      </div>
      <hr class="mini-break">
    </div>

  </div>
</div>
<div class="comments-for-<%= pricing_plan.id %>">
  <%= render 'comments/comment_thread', parent: pricing_plan %>
</div>

app/views/pricing_plans/_show.html.erb
<div id="workspace-right" class="primary-sheet sub-tool-single-view workspace-right pp-tab-item">
  <div class="tool-with-comment" data-pricing-plan-id="<%= @sub_tool_resource.id %>">
    <%= render 'pricing_plans/pricing_plan_modal_content', pricing_plan: @sub_tool_resource %>
  </div>
</div>

app/views/pricing_plans/create.js.erb
(function () {

  $newRecord = $('<%= j render 'pricing_plans/pricing_plan_card', pricing_plan: @pricing_plan %>').hide();

  $('[data-step-table-id="15"]')
      .find('[data-stage="<%= @pricing_plan.stage %>"]')
      .append($newRecord);

  $newRecord.slideDown('fast').trigger('click');

}).call(this);

app/views/pricing_plans/destroy.js.erb
$('[data-object="pricing_plan"][data-url="/pricing_plans/<%= @pricing_plan.id %>"]').slideUp(function () {
  $(this).remove()
});

app/views/pricing_plans/show.html.erb
<%= render 'pricing_plans/show' %>

app/views/pricing_plans/show.js.erb
edison.insertTab('<%= j @sub_tool_title  %>', '<%= j render "pricing_plans/show" %>', '<%= @sub_tool_resource.friendly_link %>');nanobar.loader.go(100);