config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  ## PUBLIC PAGES
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/support', to: 'static_pages#support', via: 'get'
  match '/email_validate', to: 'email_validation#validation', via: 'post'

  ## PRIVATE PAGES

  # onboarding
  match '/mass_create', to: 'businesses#mass_create', via: :post, as: 'mass_create'

  # app

  match '/customer_feedbacks/new', to: 'customer_feedbacks#new', via: 'get', as: 'new_customer_feedback'

  match 'features/get_sub_features', to: 'features#get_sub_features', via: 'post'

  match '/discussions', to: 'discussions#index', via: 'get', as: 'discussions'
  match '/discussions/new', to: 'discussions#new', via: 'get', as: 'new_discussion'
  match '/discussions/load_more', to: 'discussions#load_more', via: 'get', as: 'more_discussions'
  match '/discussions/:id', to: 'discussions#show', via: 'get', as: 'discussion'

  match '/notes', to: 'notes#index', via: 'get', as: 'notes'
  match '/notes/new', to: 'notes#new', via: 'get', as: 'new_note'
  match '/notes/:id', to: 'notes#show', via: 'get', as: 'note'
  match '/notes/:id/edit', to: 'notes#edit', via: 'get', as: 'edit_note'

  match '/to-do-lists/new', to: 'user_tasks#new', via: 'get', as: 'new_to_do_list'
  match '/to-do-lists', to: 'user_tasks#index', via: 'get', as: 'to_do_lists'
  match '/to-do-lists/archived', to: 'user_tasks#index', via: 'get', as: 'archived_to_do_lists'
  match '/sub_tasks/clear_today', to: 'sub_tasks#clear_today', via: 'post', as: 'clear_todays_tasks'
  match '/to-do-lists/:id', to: 'user_tasks#show', via: 'get', as: 'to_do_list'
  match '/sub_tasks/(:scope)/(:id)', to: 'sub_tasks#index', via: :get, as: 'sub_tasks'


  match '/sub-features/:id/feedbacks', to: 'components#feedbacks', via: :get, as: 'component_feedbacks'

  match '/customer-insights/:id', to: 'customer_feedbacks#show', via: 'get', as: 'customer_insight'
  match '/customer_feedbacks/remove_references/:id', to: 'customer_feedbacks#remove_references', via: 'get', as: 'remove_references'
  match '/customer_feedbacks/revoke_decision/:id', to: 'customer_feedbacks#revoke_decision', via: 'get', as: 'revoke_decision'
  match '/customer_feedbacks/(:scope)/(:tool)', to: 'customer_feedbacks#index', via: 'get', as: 'customer_feedbacks'

  match '/to-dos/:id', to: 'sub_tasks#show', via: :get, as: 'to_do'
  match '/milestones/:id', to: 'main_activities#show', via: :get, as: 'milestone'
  match '/cores/:id', to: 'comp_advantages#show', via: :get, as: 'core'
  match '/business-models/:id', to: 'pricing_models#show', via: :get, as: 'business_model'
  match '/pricing-plans/:id', to: 'pricing_plans#show', via: :get, as: 'pricing_plan'


  match '/onboarding', to: 'dynamic_pages#onboarding', via: 'get', as: 'onboarding'
  match '/app/(:view)', to: 'tool_pages#app', via: 'get', as: 'app'
  match '/make', to: 'dynamic_pages#make', via: 'get', as: 'make'
  match '/settings', to: 'dynamic_pages#settings', via: 'get', as: 'settings'
  match '/home', to: 'dynamic_pages#home', via: 'get', as: 'home'
  match '/toolkit', to: 'dynamic_pages#toolkit', via: 'get', as: 'toolkit'
  match '/strategy-toolkit', to: 'dynamic_pages#strategy_toolkit', via: 'get', as: 'strategy_toolkit'
  match '/milestones', to: 'dynamic_pages#milestones', via: 'get', as: 'milestones'
  match '/team', to: 'dynamic_pages#team', via: 'get', as: 'team'
  match '/customer-insights', to: 'dynamic_pages#customer_insights', via: 'get', as: 'customer_insights'

  match '/chat', to: 'dynamic_pages#chat', via: 'get', as: 'chat'
  match '/products', to: 'dynamic_pages#products', via: 'get', as: 'products_dashboard'
  match '/markets', to: 'dynamic_pages#markets', via: 'get', as: 'markets'
  match '/welcome', to: 'dynamic_pages#welcome', via: 'get', as: 'welcome'
  match '/four-pillars', to: 'dynamic_pages#four_pillars', via: 'get', as: 'four_pillars'
  match '/top-pitfalls', to: 'dynamic_pages#top_pitfalls', via: 'get', as: 'top_pitfalls'


  # ADMIN
  match '/returning_users', to: 'static_pages#returning_users', via: 'get', as: 'returning_users'


  # SCRIPTS
  match '/invite_cofounders', to: 'memberships#invite_cofounders', via: 'get', as: 'invite_cofounders'
  match '/products/update_stage', to: 'products#update_stage', via: 'put', as: 'update_stage'

  match '/refresh_activity_feed', to: 'dynamic_pages#refresh_activity_feed', via: 'get', as: 'refresh_activity_feed'

  match 'delete_business/:id', to: 'businesses#delete_business', via: 'get', as: :delete_business


  ## switch beachhead and products

  match '/update_beachhead', to: 'beachheads#update', via: 'put', as: 'update_beachhead'
  match '/switch_product', to: 'active_products#update', via: 'put', as: 'switch_product'

  ## rank persona details
  match '/persona_details/:id/rank', to: 'persona_details#rank', via: 'put', as: 'persona_details_rank'


  ## STRIPE PAYMENT GATEWAY
  match '/my_account', to: 'subscriptions#my_account', via: 'get', as: 'account'
  match '/new_subscription', to: 'subscriptions#create', via: 'post', as: 'new_subscription'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  match '/cancel_subscription', to: 'subscriptions#cancel', via: [:get, :post]
  match '/unsubscribe', to: 'subscriptions#unsubscribe', via: 'get', as: 'unsubscribe'
  mount StripeEvent::Engine, at: '/webhooks'

  ## EMAIL RECIEVING

  # match '/email_processor', to: 'emails#create', via: :post

  match '/email_processor', to: 'griddler/emails#create', via: :post


  ## DEVISE ROUTES

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    match '/sign_up', to: 'users/registrations#new', via: 'get', as: 'sign_up'
    match '/sign_in', to: 'users/sessions#new', via: 'get', as: 'sign_in'
    match '/sign_out', to: 'users/sessions#destroy', via: 'get'
    match '/delete_account', to: 'users/registrations#delete_account', via: 'post', as: 'delete_account'
    match '/forgot_password', to: 'users/passwords#new', via: 'get', as: 'forgot_password'
    match '/users_time_zone', to: 'users/registrations#users_time_zone', via: 'post'
    match '/update_missing_data', to: 'users/registrations#update_missing_data', via: 'post'
  end


  ## SIDEKIQ WEB INTERFACE

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get '.well-known/acme-challenge/AmyfUECPpG2ZdFsbTiXkAw4GSfVWPtKFM9IqYLCYKsA', to: 'static_pages#lets_encrypt'

  ## RESOURCES

  # CREATE ONLY

  resources :usage_durations, :opinions, only: [:create]

  # CREATE, UPDATE, DESTROY, INDEX

  resources :products

  # CREATE, UPDATE, DESTROY

  resources :businesses, :business_parameters, :endusers, :personas, :persona_details, :benefits,
            :value_metrics, :next_customers, :pricing_models, :sales_strategies, :comp_advantages,
            :comp_positions, :procurement_steps, :pitches, :relationship_steps, :cx_steps,
            :feedbacks, :key_activities, :features, :main_activities, :improvements,
            :innovations, :attractions, :pricing_plans, :iterations, :strategy_gaps, :user_priorities,
            :plan_defects, :sub_tasks, :experiments, :memberships, :messages, :customers, :issues,
            :components, :customer_feedbacks, :sub_components, :checklist_items, :dashboards, only: [:create, :update, :destroy]

  resources(:discussions, :notes, :customer_feedbacks, :user_tasks, :sub_tasks,
            :main_activities, :comp_advantages, :pricing_models, :pricing_plans,
            only: [:create, :update, :destroy]) do

    resources :comments, only: [:create, :update, :destroy]

  end


  # CREATE, UPDATE, DESTROY, AND EDIT

  resources :user_parameters, only: [:create, :update, :destroy, :edit]

  # ONLY UPDATE

  resources :touchpoints, :financials, :customer_decision_making_units, only: [:update]

  # ONLY SHOW

  resources :referrals, only: [:show]


end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper

  def plans
    {
        0 => {name: 'regular', price: 34},
        1 => {name: 'early_adopter', price: 24},
        2 => {name: 'special', price: 14}
    }
  end

  def plan_name
    plans[current_user.eligible_plan][:name].humanize.capitalize
  end

  def price
    plans[current_user.eligible_plan][:price]
  end

  def countries
    {
        us: "United States",
        gb: "United Kingdom",
        af: "Afghanistan",
        ax: "Åland Islands",
        al: "Albania",
        dz: "Algeria",
        as: "American Samoa",
        ad: "Andorra",
        ao: "Angola",
        ai: "Anguilla",
        aq: "Antarctica",
        ag: "Antigua and Barbuda",
        ar: "Argentina",
        am: "Armenia",
        aw: "Aruba",
        au: "Australia",
        at: "Austria",
        az: "Azerbaijan",
        bs: "Bahamas",
        bh: "Bahrain",
        bd: "Bangladesh",
        bb: "Barbados",
        by: "Belarus",
        be: "Belgium",
        bz: "Belize",
        bj: "Benin",
        bm: "Bermuda",
        bt: "Bhutan",
        bo: "Bolivia",
        ba: "Bosnia and Herzegovina",
        bw: "Botswana",
        bv: "Bouvet Island",
        br: "Brazil",
        io: "British Indian Ocean Territory",
        bn: "Brunei Darussalam",
        bg: "Bulgaria",
        bf: "Burkina Faso",
        bi: "Burundi",
        kh: "Cambodia",
        cm: "Cameroon",
        ca: "Canada",
        cv: "Cape Verde",
        ky: "Cayman Islands",
        cf: "Central African Republic",
        td: "Chad",
        cl: "Chile",
        cn: "China",
        cx: "Christmas Island",
        cc: "Cocos (Keeling) Islands",
        co: "Colombia",
        km: "Comoros",
        cg: "Congo",
        cd: "Congo",
        ck: "Cook Islands",
        cr: "Costa Rica",
        ci: "Cote D'ivoire",
        hr: "Croatia",
        cu: "Cuba",
        cy: "Cyprus",
        cz: "Czech Republic",
        dk: "Denmark",
        dj: "Djibouti",
        dm: "Dominica",
        do: "Dominican Republic",
        ec: "Ecuador",
        eg: "Egypt",
        sv: "El Salvador",
        gq: "Equatorial Guinea",
        er: "Eritrea",
        ee: "Estonia",
        et: "Ethiopia",
        fk: "Falkland Islands (Malvinas)",
        fo: "Faroe Islands",
        fj: "Fiji",
        fi: "Finland",
        fr: "France",
        gf: "French Guiana",
        pf: "French Polynesia",
        tf: "French Southern Territories",
        ga: "Gabon",
        gm: "Gambia",
        ge: "Georgia",
        de: "Germany",
        gh: "Ghana",
        gi: "Gibraltar",
        gr: "Greece",
        gl: "Greenland",
        gd: "Grenada",
        gp: "Guadeloupe",
        gu: "Guam",
        gt: "Guatemala",
        gg: "Guernsey",
        gn: "Guinea",
        gw: "Guinea-bissau",
        gy: "Guyana",
        ht: "Haiti",
        hm: "Heard Island and Mcdonald Islands",
        va: "Holy See (Vatican City State)",
        hn: "Honduras",
        hk: "Hong Kong",
        hu: "Hungary",
        is: "Iceland",
        in: "India",
        id: "Indonesia",
        ir: "Iran",
        iq: "Iraq",
        ie: "Ireland",
        im: "Isle of Man",
        il: "Israel",
        it: "Italy",
        jm: "Jamaica",
        jp: "Japan",
        je: "Jersey",
        jo: "Jordan",
        kz: "Kazakhstan",
        ke: "Kenya",
        ki: "Kiribati",
        kp: "Korea",
        kr: "Korea",
        kw: "Kuwait",
        kg: "Kyrgyzstan",
        la: "Lao People's Democratic Republic",
        lv: "Latvia",
        lb: "Lebanon",
        ls: "Lesotho",
        lr: "Liberia",
        ly: "Libyan Arab Jamahiriya",
        li: "Liechtenstein",
        lt: "Lithuania",
        lu: "Luxembourg",
        mo: "Macao",
        mk: "Macedonia",
        mg: "Madagascar",
        mw: "Malawi",
        my: "Malaysia",
        mv: "Maldives",
        ml: "Mali",
        mt: "Malta",
        mh: "Marshall Islands",
        mq: "Martinique",
        mr: "Mauritania",
        mu: "Mauritius",
        yt: "Mayotte",
        mx: "Mexico",
        fm: "Micronesia",
        md: "Moldova",
        mc: "Monaco",
        mn: "Mongolia",
        me: "Montenegro",
        ms: "Montserrat",
        ma: "Morocco",
        mz: "Mozambique",
        mm: "Myanmar",
        na: "Namibia",
        nr: "Nauru",
        np: "Nepal",
        nl: "Netherlands",
        an: "Netherlands Antilles",
        nc: "New Caledonia",
        nz: "New Zealand",
        ni: "Nicaragua",
        ne: "Niger",
        ng: "Nigeria",
        nu: "Niue",
        nf: "Norfolk Island",
        mp: "Northern Mariana Islands",
        no: "Norway",
        om: "Oman",
        pk: "Pakistan",
        pw: "Palau",
        ps: "Palestinian Territory",
        pa: "Panama",
        pg: "Papua New Guinea",
        py: "Paraguay",
        pe: "Peru",
        ph: "Philippines",
        pn: "Pitcairn",
        pl: "Poland",
        pt: "Portugal",
        pr: "Puerto Rico",
        qa: "Qatar",
        re: "Reunion",
        ro: "Romania",
        ru: "Russian Federation",
        rw: "Rwanda",
        sh: "Saint Helena",
        kn: "Saint Kitts and Nevis",
        lc: "Saint Lucia",
        pm: "Saint Pierre and Miquelon",
        vc: "Saint Vincent and The Grenadines",
        ws: "Samoa",
        sm: "San Marino",
        st: "Sao Tome and Principe",
        sa: "Saudi Arabia",
        sn: "Senegal",
        rs: "Serbia",
        sc: "Seychelles",
        sl: "Sierra Leone",
        sg: "Singapore",
        sk: "Slovakia",
        si: "Slovenia",
        sb: "Solomon Islands",
        so: "Somalia",
        za: "South Africa",
        gs: "South Georgia and The South Sandwich Islands",
        es: "Spain",
        lk: "Sri Lanka",
        sd: "Sudan",
        sr: "Suriname",
        sj: "Svalbard and Jan Mayen",
        sz: "Swaziland",
        se: "Sweden",
        ch: "Switzerland",
        sy: "Syrian Arab Republic",
        tw: "Taiwan",
        tj: "Tajikistan",
        tz: "Tanzania",
        th: "Thailand",
        tl: "Timor-leste",
        tg: "Togo",
        tk: "Tokelau",
        to: "Tonga",
        tt: "Trinidad and Tobago",
        tn: "Tunisia",
        tr: "Turkey",
        tm: "Turkmenistan",
        tc: "Turks and Caicos Islands",
        tv: "Tuvalu",
        ug: "Uganda",
        ua: "Ukraine",
        ae: "United Arab Emirates",
        um: "United States Minor Outlying Islands",
        uy: "Uruguay",
        uz: "Uzbekistan",
        vu: "Vanuatu",
        ve: "Venezuela",
        vn: "Viet Nam",
        vg: "Virgin Islands",
        vi: "Virgin Islands",
        wf: "Wallis and Futuna",
        eh: "Western Sahara",
        ye: "Yemen",
        zm: "Zambia",
        zw: "Zimbabwe"}

  end

end

app/views/subscriptions/_card_form.html.erb
<%= form_tag form_action, id: "payment-form" do %>



    <div class="card-details-enc">

      <span class="payment-errors"></span>

      <!--<h5>Card Information</h5>-->
      <div class="payment-row">
        <p class="card-name-enc"><%= text_field_tag 'name_on_card', nil, :class => "normal-input card-name", placeholder: 'Name on Card' %></p>
      </div>

      <div class="secure-area">
      <p class="card-num-enc"><%= telephone_field_tag nil, nil, name: nil, :data => {:stripe => 'number'}, :class => "normal-input cc-num card-num", placeholder:'Card number' %><span class="card-logo"></span></p>

      <div class="clearfix attached-details-enc row">
        <div class="col-xs-4 expiry-date-enc"><%= telephone_field_tag nil, nil, name: nil, :placeholder => "MM/YYYY", size: 6, :data => {:stripe => 'exp-month'}, :class => "normal-input cc-exp" %></div>
        <div class="col-xs-3 cvv-enc"><%= telephone_field_tag nil, nil, name: nil, :placeholder => "CVC", :data => {:stripe => 'cvc'}, class: "normal-input cc-cvc" %></div>
        <div class="col-xs-5 secure-icon">
          <i class="fa fa-question-circle" data-placement="right" data-toggle="tooltip" title="The security code is a 3 or 4 digit code printed on your credit card. We require this code as a security measure to our customers. Requiring this information helps to ensure that the credit card is present at the time of purchase."></i>
          <div class="authentic-payment-seperate">
            <section class="discover"></section>
            <section class="american-express"></section>
            <section class="master"></section>
            <section class="visa"></section>
          </div>
        </div>


      </div>

      </div>

      <!--<h5>Billing Information</h5>-->

      <div class="payment-row">
        <p class="card-address-enc"><%= text_field_tag 'address_line', nil, :class => "normal-input address-line", placeholder: 'Address' %></p>
      </div>

      <div class="payment-row row">
        <div class="col-xs-6">


          <p class="card-city-enc"><%= text_field_tag 'city', nil, :class => "normal-input city-name", placeholder: 'City' %></p>
        </div>
        <div class="col-xs-6">


          <p class="card-state-enc"><%= text_field_tag 'state', nil, :class => "normal-input state-name", placeholder: 'State/Province' %></p>
        </div>
      </div>
      <div class="payment-row row">
        <div class="col-xs-6">

          <p class="card-country-enc"><%= collection_select 'country', nil, countries, :first, :last, :class => "normal-input country-name", placeholder: 'Country' %></p>
        </div>
        <div class="col-xs-6">


          <p class="card-zip-enc"><%= text_field_tag 'postal_code', nil, :class => "normal-input zip-code", placeholder: 'ZIP/Postal Code' %></p>
        </div>
      </div>

      <h3 class="hidden payment-sec-title">Billing address</h3>

      <div class="hidden user-details-enc">





      </div>

    </div>

    <div class="plan-subscribe-btn-enc"><%= button_tag button_name, :class => "btn btn-primary plan-subscribe-btn", data: {disable_with: 'Processing...', button_name:button_name} %></div>

<% end %>

app/views/subscriptions/my_account.html.erb
<div class="container">

  <%= link_to app_path(view: 'home') do %>
      <%= image_tag 'oneLogo.png', class: 'bulb-logo' %>
  <% end %>

  <%= cl_image_tag('stripe_logo', class: "authentic-img stripe pull-right", :secure => true) %>

  <% if current_user.active_subscriber? || current_user.unpaid_subscriber? %>


      <div id="plan-container">

        <div class="detail-explanations">

          <div class="detail-explanations-inner">
            <h3 class="payment-page-title">You are subscribed to EdisonPlan.</h3>

            <p class="exp-date-container">Your current subscription ends on
              <span class="exp-date"><%= ldt(current_user.current_subscription_end_at) %></span>.</p>

            <p>
              <a class="update-card-trigger">Update your card information</a>
              <%= link_to "Unsubscribe", unsubscribe_path, class: "unsub-link", remote: true %>
            </p>

          </div>
        </div>


        <div class="update-card-enc" style="display: none">
          <a class="back-button">&larr; Back</a>
          <%= render 'subscriptions/card_form', form_action: update_card_path, button_name: 'Update Card' %>

        </div>

        <div class="modal fade del-business">
          <div class="modal-dialog center-modal-dialog deep modal-md">
            <div id="del-business-content" class="transparent-modal del-business-content modal-content">

            </div>
          </div>
        </div>

      </div>


  <% else %>


      <div id="plan-container" class="app-page-container plan-container-enc">
        <h3 class="inner-app-title payment-page-title text-center">Subscribe to EdisonPlan</h3>
        <%= render 'subscriptions/card_form', form_action: new_subscription_path, button_name: "Subscribe for $#{price} a month" %>
      </div>


  <% end %>

  <div class="payment-footer"><%= link_to 'Terms of Service', terms_path, target: '_blank' %>
    | <%= link_to 'Privacy Policy', privacy_path, target: '_blank' %> | Copyright 2015 EdisonPlan.com All rights
    reserved.
  </div>


</div>

app/views/subscriptions/unsubscribe.js.erb
$('#del-business-content').html('<%= j render 'static_pages/shared/unsubsribe_confirmation' %>');
$('.del-business').modal('show');