config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  ## PUBLIC PAGES
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/support', to: 'static_pages#support', via: 'get'
  match '/email_validate', to: 'email_validation#validation', via: 'post'

  ## PRIVATE PAGES

  # onboarding
  match '/mass_create', to: 'businesses#mass_create', via: :post, as: 'mass_create'

  # app

  match '/customer_feedbacks/new', to: 'customer_feedbacks#new', via: 'get', as: 'new_customer_feedback'

  match 'features/get_sub_features', to: 'features#get_sub_features', via: 'post'

  match '/discussions', to: 'discussions#index', via: 'get', as: 'discussions'
  match '/discussions/new', to: 'discussions#new', via: 'get', as: 'new_discussion'
  match '/discussions/load_more', to: 'discussions#load_more', via: 'get', as: 'more_discussions'
  match '/discussions/:id', to: 'discussions#show', via: 'get', as: 'discussion'

  match '/notes', to: 'notes#index', via: 'get', as: 'notes'
  match '/notes/new', to: 'notes#new', via: 'get', as: 'new_note'
  match '/notes/:id', to: 'notes#show', via: 'get', as: 'note'
  match '/notes/:id/edit', to: 'notes#edit', via: 'get', as: 'edit_note'

  match '/to-do-lists/new', to: 'user_tasks#new', via: 'get', as: 'new_to_do_list'
  match '/to-do-lists', to: 'user_tasks#index', via: 'get', as: 'to_do_lists'
  match '/to-do-lists/archived', to: 'user_tasks#index', via: 'get', as: 'archived_to_do_lists'
  match '/sub_tasks/clear_today', to: 'sub_tasks#clear_today', via: 'post', as: 'clear_todays_tasks'
  match '/to-do-lists/:id', to: 'user_tasks#show', via: 'get', as: 'to_do_list'
  match '/sub_tasks/(:scope)/(:id)', to: 'sub_tasks#index', via: :get, as: 'sub_tasks'


  match '/sub-features/:id/feedbacks', to: 'components#feedbacks', via: :get, as: 'component_feedbacks'

  match '/customer-insights/:id', to: 'customer_feedbacks#show', via: 'get', as: 'customer_insight'
  match '/customer_feedbacks/remove_references/:id', to: 'customer_feedbacks#remove_references', via: 'get', as: 'remove_references'
  match '/customer_feedbacks/revoke_decision/:id', to: 'customer_feedbacks#revoke_decision', via: 'get', as: 'revoke_decision'
  match '/customer_feedbacks/(:scope)/(:tool)', to: 'customer_feedbacks#index', via: 'get', as: 'customer_feedbacks'

  match '/to-dos/:id', to: 'sub_tasks#show', via: :get, as: 'to_do'
  match '/milestones/:id', to: 'main_activities#show', via: :get, as: 'milestone'
  match '/cores/:id', to: 'comp_advantages#show', via: :get, as: 'core'
  match '/business-models/:id', to: 'pricing_models#show', via: :get, as: 'business_model'
  match '/pricing-plans/:id', to: 'pricing_plans#show', via: :get, as: 'pricing_plan'


  match '/onboarding', to: 'dynamic_pages#onboarding', via: 'get', as: 'onboarding'
  match '/app/(:view)', to: 'tool_pages#app', via: 'get', as: 'app'
  match '/make', to: 'dynamic_pages#make', via: 'get', as: 'make'
  match '/settings', to: 'dynamic_pages#settings', via: 'get', as: 'settings'
  match '/home', to: 'dynamic_pages#home', via: 'get', as: 'home'
  match '/toolkit', to: 'dynamic_pages#toolkit', via: 'get', as: 'toolkit'
  match '/strategy-toolkit', to: 'dynamic_pages#strategy_toolkit', via: 'get', as: 'strategy_toolkit'
  match '/milestones', to: 'dynamic_pages#milestones', via: 'get', as: 'milestones'
  match '/team', to: 'dynamic_pages#team', via: 'get', as: 'team'
  match '/customer-insights', to: 'dynamic_pages#customer_insights', via: 'get', as: 'customer_insights'

  match '/chat', to: 'dynamic_pages#chat', via: 'get', as: 'chat'
  match '/products', to: 'dynamic_pages#products', via: 'get', as: 'products_dashboard'
  match '/markets', to: 'dynamic_pages#markets', via: 'get', as: 'markets'
  match '/welcome', to: 'dynamic_pages#welcome', via: 'get', as: 'welcome'
  match '/four-pillars', to: 'dynamic_pages#four_pillars', via: 'get', as: 'four_pillars'
  match '/top-pitfalls', to: 'dynamic_pages#top_pitfalls', via: 'get', as: 'top_pitfalls'


  # ADMIN
  match '/returning_users', to: 'static_pages#returning_users', via: 'get', as: 'returning_users'


  # SCRIPTS
  match '/invite_cofounders', to: 'memberships#invite_cofounders', via: 'get', as: 'invite_cofounders'
  match '/products/update_stage', to: 'products#update_stage', via: 'put', as: 'update_stage'

  match '/refresh_activity_feed', to: 'dynamic_pages#refresh_activity_feed', via: 'get', as: 'refresh_activity_feed'

  match 'delete_business/:id', to: 'businesses#delete_business', via: 'get', as: :delete_business


  ## switch beachhead and products

  match '/update_beachhead', to: 'beachheads#update', via: 'put', as: 'update_beachhead'
  match '/switch_product', to: 'active_products#update', via: 'put', as: 'switch_product'

  ## rank persona details
  match '/persona_details/:id/rank', to: 'persona_details#rank', via: 'put', as: 'persona_details_rank'


  ## STRIPE PAYMENT GATEWAY
  match '/my_account', to: 'subscriptions#my_account', via: 'get', as: 'account'
  match '/new_subscription', to: 'subscriptions#create', via: 'post', as: 'new_subscription'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  match '/cancel_subscription', to: 'subscriptions#cancel', via: [:get, :post]
  match '/unsubscribe', to: 'subscriptions#unsubscribe', via: 'get', as: 'unsubscribe'
  mount StripeEvent::Engine, at: '/webhooks'

  ## EMAIL RECIEVING

  # match '/email_processor', to: 'emails#create', via: :post

  match '/email_processor', to: 'griddler/emails#create', via: :post


  ## DEVISE ROUTES

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    match '/sign_up', to: 'users/registrations#new', via: 'get', as: 'sign_up'
    match '/sign_in', to: 'users/sessions#new', via: 'get', as: 'sign_in'
    match '/sign_out', to: 'users/sessions#destroy', via: 'get'
    match '/delete_account', to: 'users/registrations#delete_account', via: 'post', as: 'delete_account'
    match '/forgot_password', to: 'users/passwords#new', via: 'get', as: 'forgot_password'
    match '/users_time_zone', to: 'users/registrations#users_time_zone', via: 'post'
    match '/update_missing_data', to: 'users/registrations#update_missing_data', via: 'post'
  end


  ## SIDEKIQ WEB INTERFACE

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get '.well-known/acme-challenge/AmyfUECPpG2ZdFsbTiXkAw4GSfVWPtKFM9IqYLCYKsA', to: 'static_pages#lets_encrypt'

  ## RESOURCES

  # CREATE ONLY

  resources :usage_durations, :opinions, only: [:create]

  # CREATE, UPDATE, DESTROY, INDEX

  resources :products

  # CREATE, UPDATE, DESTROY

  resources :businesses, :business_parameters, :endusers, :personas, :persona_details, :benefits,
            :value_metrics, :next_customers, :pricing_models, :sales_strategies, :comp_advantages,
            :comp_positions, :procurement_steps, :pitches, :relationship_steps, :cx_steps,
            :feedbacks, :key_activities, :features, :main_activities, :improvements,
            :innovations, :attractions, :pricing_plans, :iterations, :strategy_gaps, :user_priorities,
            :plan_defects, :sub_tasks, :experiments, :memberships, :messages, :customers, :issues,
            :components, :customer_feedbacks, :sub_components, :checklist_items, :dashboards, only: [:create, :update, :destroy]

  resources(:discussions, :notes, :customer_feedbacks, :user_tasks, :sub_tasks,
            :main_activities, :comp_advantages, :pricing_models, :pricing_plans,
            only: [:create, :update, :destroy]) do

    resources :comments, only: [:create, :update, :destroy]

  end


  # CREATE, UPDATE, DESTROY, AND EDIT

  resources :user_parameters, only: [:create, :update, :destroy, :edit]

  # ONLY UPDATE

  resources :touchpoints, :financials, :customer_decision_making_units, only: [:update]

  # ONLY SHOW

  resources :referrals, only: [:show]


end

app/models/customer_feedback.rb
class CustomerFeedback < ActiveRecord::Base
  belongs_to :product
  has_many :comments
  include CommentsHelper::InstanceMethods

  scope :critical, -> { where(customer_interest: 1..2) }
  scope :unaddressed, -> { where(decision: nil) }
  scope :scheduled, -> { where(decision: 1) }
  scope :disregarded, -> { where(decision: 2) }
  scope :completed, -> { where(decision: 3) }
  scope :for_sub_feature, -> (sub_feature_id) { where(related_component_id: sub_feature_id) }
  scope :for_tool, -> (tool) { where(related_tool: tool) }


  attr_accessor :feedback_comment

  DECISION = {
      1 => 'Schedule response',
      2 => 'Disregard',
      3 => 'Completed',
  }

  default_scope { order('customer_feedbacks.created_at DESC') }

  after_create :generate_secret_token
  after_create :notify_team

  validates :feedback, presence: true
  validates :customer_name, presence: true


  def generate_secret_token
    update_attributes(secret_token: "reply-F-#{SecureRandom.urlsafe_base64}")
  end


  def descriptive_status
    case decision
      when 1
        'response scheduled'
      when 2
        'disregarded'
      when 3
        'completed'
      else
        'unaddressed'
    end
  end


  def user
    User.where(id: created_by).first || product.user
  end

  def notify_team
    CustomerFeedbackMailWorker.perform_async(self.id)
  end

  def feedback_title
    "#{customer_name}'s feedback on #{created_at.strftime('%d %b %Y')}"
  end

  def title_for_email
    feedback_title
  end

  def related_feature
    Feature.find(related_feature_id) if related_feature_id
  end

  def related_component
    Component.find(related_component_id) if related_component_id
  end

  def categorized?
    [related_tool, related_feature_id, related_component_id].any?
  end

  def reference_tag

    if related_tool
      [related_tool, STEP[related_tool][:name]]
    elsif related_component_id && related_feature_id
      [nil, "#{related_feature.feature_name} &rsaquo;&rsaquo; #{related_component.name}"]
    end

  end

  def remove_reference_tags
    update_attributes(
        related_feature_id: nil,
        related_component_id: nil,
        related_tool: nil
    )
  end

  def revoke_decision
    update_attributes(
        status: nil,

    )
  end

  def actionable?
    decision == 1
  end

  def assignee
    User.where(id: assigned_to).first
  end


  def friendly_link
    "/customer-insights/#{id}"
  end


end

app/controllers/customer_feedbacks_controller.rb
class CustomerFeedbacksController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_business, only: [:destroy, :update, :remove_references, :revoke_decision]


  def unaddressed


  end


  def remove_references
    @customer_feedback.remove_reference_tags
  end

  def revoke_decision
    @customer_feedback.revoke_decision
  end

  def index
    set_tool if params[:tool]
    set_scope if params[:scope]

    @feedbacks = if @tool
                   active_product.customer_feedbacks.send(@scope).for_tool(@step)
                 else
                   active_product.customer_feedbacks.send(@scope)
                 end
    @view = "#{@scope.capitalize} Feedback #{"for #{@tool}" if @tool}"
    @url = customer_feedbacks_path(scope: @scope, tool: @tool)
    @tab_title = "#{@scope.capitalize} Feedback #{"for #{@tool}" if @tool}"
  end

  def new
    @new_sub_tool_title = 'New Customer Feedback'
  end

  def show
    @sub_tool_resource = active_product.customer_feedbacks.find(params[:id])
    @sub_tool_title = "Insights from #{@sub_tool_resource.customer_name}"
    respond_to do |format|
      format.html
      format.js
    end
  end



  def create

    @customer_feedback = active_product.customer_feedbacks.build(customer_feedback_params.merge(created_by: current_user.id))
    respond_to do |format|
      if @customer_feedback.save
        @customer_feedback.comments.create(user_id: current_user.id, comment_text: params[:customer_feedback][:feedback_comment]) if params[:customer_feedback][:feedback_comment]
        format.js
        format.html { redirect_to :back }
        FeedbackAssignmentMailWorker.perform_async(current_user.id, @customer_feedback.id) if @field == :assigned_to && @customer_feedback.assigned_to
      else
        format.html { redirect_to :back }
        format.js {}
      end
    end

  end

  def destroy

    respond_to do |format|
      @customer_feedback.destroy
      format.html { redirect_to :back }
      format.js
    end

  end


  def update
    respond_to do |format|
      if @customer_feedback.update_attributes(customer_feedback_params)
        format.json { respond_with_bip(@customer_feedback) }
        format.js { respond_with_active_edit @customer_feedback, @field }
        format.html { redirect_to :back }

      else
        format.html { redirect_to :back }
      end
    end
  end

  private


  def customer_feedback_params
    params.require(:customer_feedback).permit(:customer_name,
                                              :feedback,
                                              :related_feature_id,
                                              :related_component_id,
                                              :customer_interest,
                                              :critical, :status, :created_by,
                                              :related_tool, :decision, :assigned_to, :target_date
    )
  end


  def correct_business
    @customer_feedback = active_product.customer_feedbacks.find_by(id: params[:id])
    if @customer_feedback.nil?
      redirect_to root_url
    end
  end


  def set_tool
    requested_view = params[:tool]
    @tool = permitted_views.include?(requested_view) ? requested_view : nil
    @step = all_tools[@tool]
  end

  def set_scope
    requested_scope = params[:scope]
    @scope = ['all', 'unaddressed', 'scheduled', 'disregarded', 'completed'].include?(requested_scope) ? requested_scope : 'all'
  end


end

app/views/customer_feedbacks/_customer_feedback_body.html.erb
<div class="feedback-body">
  <%= active_edit_if has_valid_access?, @customer_feedback, :feedback %>
</div>

app/views/customer_feedbacks/_customer_feedback_modal_content.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span></button>
  <div class="modal-title">
    <%= profile_icon feedback.user %> shared
    <strong><%= ae_live_field feedback, :customer_name %></strong>'s insight on <%= ldt feedback.created_at %>
  </div>
</div>
<div class="modal-body">
  <%= render 'customer_feedbacks/customer_feedback_status_tag', feedback:feedback %>
  <div class="feedback-body">
    <%= ae_live_field feedback, :feedback %>
  </div>
  <div class="feedback-prop-section">
    <div class="feedback-prop-title">Importance to customer</div>
    <%= active_edit_if has_valid_access?, feedback, :customer_interest, type: :select, choices: star_rating, placeholder: 'Importance to customer' %>
  </div>

  <%= render 'customer_feedbacks/customer_feedback_references', feedback: feedback %>
  <%= render 'customer_feedbacks/customer_feedback_decision', feedback: feedback %>


</div>
<div class="modal-footer">
  <div class="comments-for-<%= feedback.id %>">
    <%= render 'comments/comment_thread', parent: feedback %>
  </div>
</div>

app/views/customer_feedbacks/_customer_feedback_reference_tag.html.erb
<% tag = feedback.reference_tag %>

<div style="display: inline-block;" class="feedback-ref-tag hyperlink" data-behaviour="open_in_new_tab" data-href="<%= (tag[0] ? step_href_path(tag[0]) : make_path) if tag %>">
  <%= tag[1].html_safe if tag %>
</div>

app/views/customer_feedbacks/_customer_feedback_references.html.erb
<div class="feedback-prop-section feedback-references">
  <div class="feedback-prop-title">References</div>

  <div>

    <div style="margin-top: 10px; <%= 'display:none;' if defined?(first_time) && first_time %>" class="feedback-reference-parent">

      <% unless feedback.categorized? %>

          <div>Does this insight relate to Strategy or
            Product? <%= select_tag 'feedback_type', options_for_select(["Strategy", "Product"]), prompt: 'select', class: 'select' %></div>

      <% end %>

      <div class="feedback-strategy-container">

        <div class="feature-data" style="<%= 'display: none;' unless feedback.related_feature_id %>">
          <% if beachhead.has_features? %>

              <div class="dd-tag">
                <%= active_edit_if has_valid_access?, feedback, :related_feature_id, type: :select, choices: beachhead.features.pluck(:id, :feature_name).to_h, placeholder: 'Related feature' %>
              </div>

              <% if feedback.related_feature %>
                  &rsaquo;&rsaquo;
                  <div class="dd-tag ">
                    <%= active_edit_if has_valid_access?, feedback, :related_component_id, type: :select, choices: feedback.related_feature.components.pluck(:id, :name).to_h, placeholder: 'Related sub feature' %>
                  </div>
              <% end %>

          <% else %>

              <div class=" " style="background-color: aliceblue; padding: 10px;">
                <p>If the customer insight pertains to a Product development:</p>

                <p>Product is made up multiple Features and its sub-features. The insight may pertain to
                  anyone the sub-feature. It can be a bug, or a unmet need.</p>

                <p>You can tag this insight to the most relevant sub-feature. Process the insight, decide
                  to
                  act on it or disregard the insight, based on its merit.</p>

                <p>You will be able to tag the insight once you start using
                  <span class="hyperlink" data-dismiss="modal" data-behaviour="open_in_new_tab" data-href="<%= step_href_path(7) %>">Product.</span>
                </p>
              </div>

          <% end %>
        </div>


        <div class="related-tool-data" style="<%= 'display: none;' unless feedback.related_tool %>">
          <% if beachhead.canvas_started? %>
              <div class="dd-tag">
                <%= active_edit_if has_valid_access?, feedback, :related_tool, type: :select, choices: tool_hash, placeholder: 'Related tool' %>
              </div>
          <% else %>
              <div class="" style="background-color: aliceblue; padding: 10px;">
                <p>If the customer insight pertains to a Strategy problem:</p>

                <p>Strategy is made up of 15 strategy solutions to the 15 different strategy problems. The
                  insight may pertain to anyone of the strategy tools like Beachhead, Markets, or End
                  users.</p>

                <p>You can tag this insight to the most relevant tool. Process the insight, decide to act
                  on
                  it or disregard the insight, based on its merit.</p>

                <p>You will be able to tag the insight once you start using
                  <span class="hyperlink" data-dismiss="modal" data-behaviour="open_in_new_tab" data-href="<%= strategy_toolkit_path %>">Strategy.</span>
                </p>

              </div>
          <% end %>
        </div>

      </div>

    </div>


    <% if feedback.categorized? %>
        <div style="text-align: right;">
          <div class="hyperlink" data-toggle="tooltip" data-title="Remove reference" data-behaviour="get_script" data-script-href="<%= remove_references_path(feedback.id) %>" style="font-size: .8rem;display: inline-block;">remove
            references
          </div>
        </div>
    <% end %>

  </div>


</div>

app/views/customer_feedbacks/_decision.js.erb
$feedback = $('[data-customer-feedback-id=<%= @customer_feedback.id %>]');

$feedback
    .find('.feedback-decision')
    .replaceWith('<%= j render 'customer_feedbacks/customer_feedback_decision', feedback: @customer_feedback %>');

$feedback
    .find('.feedback-status.status-tag')
    .replaceWith('<%= j render 'customer_feedbacks/customer_feedback_status_tag', feedback: @customer_feedback %>');

<%= render 'update_customer_insights' %>

app/views/customer_feedbacks/_index.html.erb
<div class="feedbacks-for-feature" style="width: 40%; margin: 30px auto;">

  <h4 style="text-align: center;margin-bottom: 30px;"><%= @scope.capitalize %> Insights <%= "for #{@tool}" if @tool %></h4>


  <% if @feedbacks.present? %>
      <% @feedbacks.each do |feedback| %>
          <%= render 'customer_feedbacks/new_feedback_item', feedback: feedback %>
      <% end %>
  <% else %>

      <div style="text-align: center;">
        <p>There are no insights yet.</p>

        <p>Do you want to record new insights? Go to
          <span class="hyperlink" data-behaviour="open_in_new_tab" data-href="<%= customer_insights_path %>">Insights</span>
        </p>
      </div>
  <% end %>

</div>

app/views/customer_feedbacks/_new_customer_feedback.html.erb
<div class="new-customer-feedback-form-enc new-sub-tool-form-enc">


  <div class="modal fade feedback-modal new-customer-feedback" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <div class="modal-title">
            New Insight
          </div>
        </div>

        <%= render 'customer_feedbacks/single_customer_feedback_form' %>


      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->


  <div class="modal fade feedback-modal new-customer-feedbacks" tabindex="-1" role="dialog">

    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <div class="modal-title">
            New Insight
          </div>
        </div>


        <div class="modal-body">
          <div class="feedback-sheet">
            <div class="ui-front">
              <%= text_field_tag :customer_name, '', class: 'form-control customer_feedback_customer_name multi-feedback-customer-name', placeholder: 'Customer name', 'data-tags': "#{active_product.feedback_providers_names}", autofocus: 'autofocus' %>
            </div>
            <div class="full-form-content multi-feedbacks-entry-list">
              <div style="margin-top: 10px;" data-feedback-enc-id="<%= r = rand_string %>">
                <%= text_area_tag :feedback, '', {class: 'form-control multi-feedback-textarea ', placeholder: 'Insight from Customer', 'data-feedback-temp-id' => r, disabled: 'disabled'} %>
              </div>
              <div style="margin-top: 10px;" data-feedback-enc-id="<%= r = rand_string %>">
                <%= text_area_tag :feedback, '', {class: 'form-control multi-feedback-textarea', placeholder: 'Insight from Customer', 'data-feedback-temp-id' => r, disabled: 'disabled'} %>
              </div>
            </div>
          </div>

        </div>
        <div class="modal-footer">

          <div class="btn-container" style="text-align: center;">
            <div class="btn-primary btn collapse-target" data-dismiss="modal">Close</div>
          </div>
        </div>


      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

</div>

app/views/customer_feedbacks/_new_feedback_actions.html.erb
<div class="only-when-none" style="<%= "display: none;" if @customer_feedbacks.count == 0 %>">
  <div class="btn-container" style="padding: 20px 0; text-align: center;">
    <div data-toggle="modal" data-target=".new-customer-feedback" class="btn btn-primary" style="width: 280px;">
      + add an insight
    </div>
    <div data-toggle="modal" data-target=".new-customer-feedbacks" class="btn btn-info" style="width: 280px;">
      + add many insights
    </div>
  </div>
</div>

app/views/customer_feedbacks/_show.html.erb
<div id="workspace-right" class="primary-sheet sub-tool-single-view workspace-right feedback-tab-item">
  <div class="tool-with-comment" data-customer-feedback-id="<%= @sub_tool_resource.id %>">
  <%= render 'customer_feedbacks/customer_feedback_modal_content', feedback: @sub_tool_resource %>
  </div>
</div>

app/views/customer_feedbacks/index.js.erb
edison.insertTab('<%= @tab_title  %>', '<%= j render "customer_feedbacks/index" %>', '<%= @url %>');
nanobar.loader.go(100);

app/views/customer_feedbacks/new.html.erb
<%= render 'customer_feedbacks/new_feedback_in_tab' %>

app/views/customer_feedbacks/remove_references.js.erb
<%= render 'customer_feedbacks/related_feature_id' %>

app/views/customer_feedbacks/show.js.erb
edison.insertTab('<%= j @sub_tool_title  %>', '<%= j render "customer_feedbacks/show" %>', '<%= @sub_tool_resource.friendly_link %>');
nanobar.loader.go(100);

app/views/customer_feedbacks/unaddressed.js.erb
edison.insertTab('<%= @tab_title  %>', '<%= j render "customer_feedbacks/unaddressed" %>', '<%= @url %>');
nanobar.loader.go(100);